version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn build
      - run: ls

workflows:
  deploying-app:
    jobs:
      - build
