version: 2.1
orbs:
  node: circleci/node@3.0.0
  python: circleci/python@0.3.0
  aws-s3: circleci/aws-s3@1.0.15
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn build
      - persist_to_workspace:
          root: .
          paths: dist/
  deploy:
    executor: python/default
    steps:
      - attach_workspace:
          at: .
      - aws-s3/sync:
          arguments: --delete
          from: dist
          to: "s3://scrumways.com"

workflows:
  deploying-app:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
